_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 0

max_steps: -1
#min_epochs: 1
max_epochs: 2
weights_summary: null
progress_bar_refresh_rate: 10
resume_from_checkpoint: null
log_every_n_steps: 500
val_check_interval: 1000
reload_dataloaders_every_n_epochs: 1
strategy: ddp
