defaults:
  - basemodule
  - /evaluation: multi_classification
  
_target_: src.module.multiclass_classification.MultiClassClassification
adapters: False
lora: False
model:
  _target_: transformers.AutoModelForSequenceClassification.from_pretrained
  num_labels: ???
  pretrained_model_name_or_path: ???