defaults:
  - basemodule
  - /evaluation: jigsaw_evaluation
  
_target_: src.module.jigsaw_classification.JigsawClassification
adapters: False
lora: False
model:
  _target_: transformers.AutoModelForSequenceClassification.from_pretrained
  num_labels: ???
  pretrained_model_name_or_path: ???