defaults:
  - basemodule
  - /evaluation: binary_classification
  
_target_: src.module.jigsaw_classification.JigsawClassification
model:
  _target_: transformers.AutoModelForSequenceClassification.from_pretrained
  num_labels: ???
  pretrained_model_name_or_path: ???